### ISSUE TITLE
Deprecated ?

### ISSUE THREAD

**Issue by picks44** [KnpLabs/KnpLastTweetsBundle#29]
Is this bundle deprecated ? I tried to use it, but I only get "No tweets" in the view... using the standard method.
Would you recommend another bundle ?

**Comment by weaverryan** [comment]
@picks44 Yea it is, and I think it stopped working recently because of an upstream library called abraham/twitteroauth. You should check out just using that directly - see #27, he had success using that there :).

**Comment by picks44** [comment]
Thks !
